import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { assertNothingRunning } from "./data-folder.js";
import { BeesProduct } from "./product.js";
import { executeProductCommand } from "./product-commands.js";
import { assertRootOnDisk, folderChoices, organizationFolderChoice, refreshFolderRoots, rootFolderChoice, rootForWorkspace, rootOnDisk, workspaceDirectory, workspaceRoot } from "./folder-roots.js";

test("root selection, inherited folders and local overrides preserve work", async (t) => {
  const temp = realpathSync.native(mkdtempSync(join(tmpdir(), "bees-folders-")));
  t.after(() => rmSync(temp, { recursive: true, force: true }));
  const app = join(temp, "app"), legacy = join(app, "workspaces"), root = join(temp, "root");
  const orgOverride = join(temp, "org-drive"), teamOverride = join(temp, "team-drive");
  for (const folder of [app, legacy, root, orgOverride, teamOverride]) mkdirSync(folder, { recursive: true });
  const saved = { ...process.env };
  t.after(() => { for (const key of ["BEES_APP_DATA", "BEES_DATA_DIR", "BEES_STATE_DIR", "BEES_DEFAULT_WORKSPACE"]) {
    if (saved[key] === undefined) delete process.env[key]; else process.env[key] = saved[key];
  } });
  process.env.BEES_APP_DATA = process.env.BEES_DATA_DIR = process.env.BEES_STATE_DIR = app;
  process.env.BEES_DEFAULT_WORKSPACE = legacy;
  writeFileSync(join(app, "device-id"), "folder-check");
  const db = new DatabaseSync(":memory:");
  t.after(() => db.close());
  const records = new Map();
  const registry = { get: (id) => records.get(id), create: async (path) => {
    const record = { id: path, path }; records.set(record.id, record); return record;
  } };
  const product = new BeesProduct(db, { live: new Map() }, null, legacy, { workspaceRegistry: registry });
  // Execution links are owned by AgentRuntime; keep only the columns this folder check needs.
  db.exec("CREATE TABLE execution_links (execution_id TEXT, workspace_id TEXT, run_directory TEXT, status TEXT)");
  const command = (input) => executeProductCommand.call(product, input.action, input);
  const { id: workspaceId, team_id: teamId } = db.prepare("SELECT id, team_id FROM workspaces LIMIT 1").get();
  const { organization_id: organizationId } = db.prepare("SELECT organization_id FROM teams WHERE id = ?").get(teamId);
  assert.equal(rootFolderChoice().folder, "");
  assert.equal(workspaceRoot(workspaceId), legacy);
  const oldRun = join(legacy, "runs", "old");
  mkdirSync(oldRun, { recursive: true }); writeFileSync(join(oldRun, "result.md"), "original result");
  db.prepare("INSERT INTO execution_links VALUES ('old', ?, 'runs/old', 'completed')").run(workspaceId);
  const oldWorkspace = workspaceDirectory(workspaceId);
  mkdirSync(oldWorkspace, { recursive: true }); writeFileSync(join(oldWorkspace, "notes.md"), "workspace notes");
  const overrideTeam = await command({ action: "create_team", organizationId, name: "Active override" });
  await command({ action: "set_folder_root", level: "team", id: overrideTeam.id, workspaceId: overrideTeam.workspaceId, directory: teamOverride });
  const overrideRoot = workspaceRoot(overrideTeam.workspaceId);
  const overrideDirectory = workspaceDirectory(overrideTeam.workspaceId);
  product.agents.live.set("override-running", { data: { workspaceId: overrideTeam.workspaceId } });
  db.prepare("INSERT INTO execution_links VALUES ('override-queued', ?, 'runs/pending', 'queued')").run(overrideTeam.workspaceId);
  const legacyTeam = await command({ action: "create_team", organizationId, name: "Active legacy" });
  const legacyRoot = workspaceRoot(legacyTeam.workspaceId);
  const legacyDirectory = workspaceDirectory(legacyTeam.workspaceId);
  writeFileSync(join(legacyDirectory, "live-notes.md"), "do not relocate");
  product.agents.live.set("legacy-running", { data: { workspaceId: legacyTeam.workspaceId } });
  assert.throws(() => assertNothingRunning(db, product.agents.live), /Wait for/, "moving the whole Bees database still requires every run to stop");
  await command({ action: "set_folder_root", level: "root", directory: root });
  assert.equal(workspaceRoot(overrideTeam.workspaceId), overrideRoot, "first global setup preserves the entire team override path");
  assert.equal(workspaceDirectory(overrideTeam.workspaceId), overrideDirectory, "first global setup leaves the active native workspace alone");
  assert.equal(workspaceRoot(legacyTeam.workspaceId), legacyRoot, "active legacy work keeps its existing root during first setup");
  assert.equal(workspaceDirectory(legacyTeam.workspaceId), legacyDirectory);
  assert.equal(folderChoices(db, legacyTeam.workspaceId).find(({ level }) => level === "team").picked, legacyRoot, "the retained legacy folder can be reset in team folder settings");
  await assert.rejects(command({ action: "set_folder_root", level: "team", id: overrideTeam.id, workspaceId: overrideTeam.workspaceId, directory: orgOverride }), /Wait for/);
  assert.equal(workspaceRoot(overrideTeam.workspaceId), overrideRoot);
  const otherRoot = join(temp, "other-root"); mkdirSync(otherRoot);
  await command({ action: "set_folder_root", level: "root", directory: otherRoot });
  assert.equal(workspaceRoot(overrideTeam.workspaceId), overrideRoot, "unrelated live and queued work do not block subsequent global changes");
  assert.equal(workspaceRoot(legacyTeam.workspaceId), legacyRoot);
  await command({ action: "set_folder_root", level: "root", directory: root });
  const orgFolder = organizationFolderChoice(db, organizationId).folder;
  const teamFolder = folderChoices(db, workspaceId).find(({ level }) => level === "team").folder;
  assert.equal(orgFolder, join(root, "personal-organization"));
  assert.equal(teamFolder, join(orgFolder, "my-team"));
  assert.equal(workspaceRoot(workspaceId), teamFolder);
  assert.equal(workspaceDirectory(workspaceId), teamFolder);
  assert.equal(registry.get(db.prepare("SELECT dsh_workspace_id AS id FROM workspaces WHERE id = ?").get(workspaceId).id).path, teamFolder);
  assert.equal(readFileSync(join(teamFolder, "notes.md"), "utf8"), "workspace notes");
  assert.equal(readFileSync(join(teamFolder, "runs/old/result.md"), "utf8"), "original result");
  assert(existsSync(join(oldRun, "result.md")));
  db.prepare("UPDATE organizations SET name = 'Renamed org' WHERE id = ?").run(organizationId);
  db.prepare("UPDATE teams SET name = 'Renamed team' WHERE id = ?").run(teamId);
  refreshFolderRoots(db);
  assert.equal(workspaceRoot(workspaceId), teamFolder, "renaming does not relocate files");
  await command({ action: "set_folder_root", level: "organization", id: organizationId, directory: orgOverride });
  assert.equal(workspaceRoot(workspaceId), join(orgOverride, "my-team"));
  await command({ action: "set_folder_root", level: "team", id: teamId, workspaceId, directory: teamOverride });
  assert.equal(workspaceRoot(workspaceId), teamOverride);
  renameSync(orgOverride, orgOverride + "-offline");
  assert(rootOnDisk(workspaceId), "a team override does not depend on the organization mount");
  await assert.rejects(command({ action: "set_folder_root", level: "team", id: teamId, workspaceId, directory: "" }), /unavailable/);
  assert.equal(workspaceRoot(workspaceId), teamOverride, "a failed reset keeps the last good folder");
  renameSync(orgOverride + "-offline", orgOverride);
  await command({ action: "set_folder_root", level: "team", id: teamId, workspaceId, directory: "" });
  renameSync(orgOverride, orgOverride + "-offline");
  assert(!rootOnDisk(workspaceId));
  assert.throws(() => assertRootOnDisk(workspaceId), /Reconnect/);
  assert.throws(() => rootForWorkspace({ organizationId, organizationName: "Renamed org", teamId: "new-team", teamName: "New", id: "new-workspace", name: "Default workspace" }), /unavailable/);
  renameSync(orgOverride + "-offline", orgOverride);
  await command({ action: "set_folder_root", level: "organization", id: organizationId, directory: "" });
  assert.equal(workspaceRoot(workspaceId), teamFolder);
  const duplicate = await command({ action: "create_team", organizationId, name: "My Team" });
  assert.notEqual(workspaceRoot(duplicate.workspaceId), teamFolder, "same folder names stay isolated");
  assert(workspaceRoot(duplicate.workspaceId).startsWith(orgFolder));
  assert(existsSync(workspaceDirectory(duplicate.workspaceId)));
  const emptyOrg = await command({ action: "create_organization", name: "Empty org" });
  await command({ action: "set_folder_root", level: "organization", id: emptyOrg.id, directory: orgOverride });
  assert.equal(organizationFolderChoice(db, emptyOrg.id).folder, orgOverride, "organizations without teams can override folders");
  db.prepare("UPDATE organization_memberships SET role = 'member' WHERE organization_id = ?").run(organizationId);
  await assert.rejects(command({ action: "set_folder_root", level: "organization", id: organizationId, directory: orgOverride }), /organization administrators/);
  db.prepare("UPDATE team_memberships SET role = 'member' WHERE team_id = ?").run(teamId);
  await assert.rejects(command({ action: "set_folder_root", level: "team", id: teamId, workspaceId, directory: teamOverride }), /permission/);
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: "" }), /Choose a root/);
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: app }), /inside Bees' own data folder/);
  const alias = join(temp, "app-alias"); symlinkSync(app, alias);
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: alias }), /inside Bees' own data folder/);
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: "relative" }));
  product.agents.live.set("running", { data: { workspaceId } });
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: teamOverride }), /Wait for/);
  product.agents.live.clear();
  db.prepare("INSERT INTO execution_links VALUES ('queued', ?, 'runs/queued', 'queued')").run(workspaceId);
  await assert.rejects(command({ action: "set_folder_root", level: "root", directory: teamOverride }), /Wait for/);
  db.prepare("DELETE FROM execution_links WHERE status = 'queued'").run();
  const newRoot = join(temp, "new-root"); mkdirSync(newRoot);
  await command({ action: "set_folder_root", level: "root", directory: newRoot });
  assert.equal(workspaceRoot(workspaceId), join(newRoot, "personal-organization", "my-team"));
  assert.equal(readFileSync(join(workspaceRoot(workspaceId), "runs/old/result.md"), "utf8"), "original result");
  assert.equal(rootFolderChoice().folder, newRoot);
  refreshFolderRoots(db);
  assert.equal(workspaceRoot(workspaceId), join(newRoot, "personal-organization", "my-team"), "choices survive restart");
  await command({ action: "set_folder_root", level: "team", id: legacyTeam.id, workspaceId: legacyTeam.workspaceId, directory: "" });
  assert.equal(workspaceRoot(legacyTeam.workspaceId), join(newRoot, "personal-organization", "active-legacy"));
  assert.equal(workspaceDirectory(legacyTeam.workspaceId), workspaceRoot(legacyTeam.workspaceId));
  assert.equal(readFileSync(join(workspaceDirectory(legacyTeam.workspaceId), "live-notes.md"), "utf8"), "do not relocate");
  assert.equal(readFileSync(join(workspaceDirectory(workspaceId), "notes.md"), "utf8"), "workspace notes", "folder changes preserve team files as well as runs");

  db.prepare(`INSERT INTO workspaces (id, team_id, name, created_at, updated_at)
    VALUES ('second-workspace', ?, 'Research workspace', '2099-01-01', '2099-01-01')`).run(teamId);
  await product.initialize();
  assert.equal(workspaceRoot("second-workspace"), workspaceRoot(workspaceId), "named workspaces share the team folder");
  assert.notEqual(workspaceDirectory("second-workspace"), workspaceDirectory(workspaceId), "native session identities remain distinct");
  assert.deepEqual(folderChoices(db, "second-workspace").map(({ level }) => level), ["organization", "team"]);
  db.prepare("UPDATE team_memberships SET role = 'admin' WHERE team_id = ?").run(teamId);
  await assert.rejects(command({ action: "set_folder_root", level: "workspace", id: "second-workspace", workspaceId: "second-workspace", directory: teamOverride }), /Workspaces use their team's folder/);

  // A saved per-workspace override migrates when idle, without redirecting an active run.
  const previous = workspaceRoot(workspaceId);
  const picks = JSON.parse(readFileSync(join(app, "roots.json"), "utf8"));
  delete picks[`team-layout:${teamId}`];
  picks[`workspace:${workspaceId}`] = teamOverride;
  writeFileSync(join(app, "roots.json"), JSON.stringify(picks));
  writeFileSync(join(teamOverride, "old-workspace-note.md"), "keep old workspace files");
  product.agents.live.set("old-running", { data: { workspaceId } });
  await product.initialize();
  assert.equal(workspaceRoot(workspaceId), teamOverride, "active legacy paths are retained until idle");
  product.agents.live.clear();
  await product.initialize();
  assert.equal(workspaceRoot(workspaceId), previous);
  assert.equal(workspaceRoot("second-workspace"), previous);
  assert.equal(readFileSync(join(previous, "old-workspace-note.md"), "utf8"), "keep old workspace files");
  assert.equal(readFileSync(join(previous, "runs/old/result.md"), "utf8"), "original result");
  assert(existsSync(join(teamOverride, "old-workspace-note.md")));
  const nested = join(temp, "nested-source"), nestedTeam = join(nested, "team");
  mkdirSync(join(nested, "runs", "nested"), { recursive: true });
  mkdirSync(nestedTeam);
  writeFileSync(join(nested, "notes.md"), "nested folder notes");
  writeFileSync(join(nested, "runs", "nested", "result.md"), "nested run result");
  db.prepare("INSERT INTO execution_links VALUES ('nested', ?, 'runs/nested', 'completed')").run(workspaceId);
  const nestedPicks = JSON.parse(readFileSync(join(app, "roots.json"), "utf8"));
  delete nestedPicks[`team-layout:${teamId}`];
  nestedPicks[`team:${teamId}`] = nestedTeam;
  nestedPicks[`workspace:${workspaceId}`] = nested;
  writeFileSync(join(app, "roots.json"), JSON.stringify(nestedPicks));
  await product.initialize();
  assert.equal(workspaceRoot(workspaceId), nestedTeam);
  assert.equal(readFileSync(join(nestedTeam, "notes.md"), "utf8"), "nested folder notes");
  assert.equal(readFileSync(join(nestedTeam, "runs", "nested", "result.md"), "utf8"), "nested run result");
  assert(!existsSync(join(nestedTeam, "team")), "a nested destination is not copied into itself");
});
